IMAGE_NAME = "ubuntu/jammy64"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "zbx-agent-ls"

  # Interní síť pro Zabbix komunikaci
  config.vm.network "private_network", ip: "192.168.1.3", virtualbox__intnet: "intnet"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
    vb.name = "zbx-agent2-lasikova"
  end

  # Provisioning tvých skriptů
  config.vm.provision "shell", path: "install-zabbix-agent2.sh"
  config.vm.provision "shell", path: "configure-zabbix-agent2.sh"
end
