IMAGE_NAME = "ubuntu/jammy64"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = IMAGE_NAME
    ubuntu.vm.hostname = "ubuntu-spos"

    # Port forwarding pro SSH
    ubuntu.vm.network "forwarded_port", guest: 22, host: 2202, host_ip: "127.0.0.1"

    # Primární NAT síť (pro přístup do internetu)
    ubuntu.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", auto_config: true, use_dhcp_assigned_default_route: true

    # Druhá síť – interní síť 192.168.1.0/24
    ubuntu.vm.network "private_network",
      ip: "192.168.1.3",
      virtualbox__intnet: true

    # Provisioning – kopírování klíče
    ubuntu.vm.provision "file", source: "id_rsa.pub", destination: "~/.ssh/me.pub"

    # Přidání klíče do authorized_keys
    ubuntu.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL

    # Spuštění instalačního skriptu pro Zabbix Agent2
    ubuntu.vm.provision "shell", path: "install-zabbix-agent2.sh"

    # Spuštění konfiguračního skriptu
    ubuntu.vm.provision "shell", path: "configure-zabbix-agent2.sh"
  end
end
